# Generated by Django 5.1.2 on 2025-01-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_test_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-created_at']},
        ),
    ]
