# Generated by Django 5.1.2 on 2024-12-31 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprojects_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProjects',
        ),
    ]
